stages:
  - build
  - make
  - artifacts

variables:
  NODE_VERSION: 18  # Можно изменить на нужную версию Node.js

# Шаг 1: Сборка проекта в минимальном Alpine-образе
build:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Шаг 2: Создание установочного пакета на Windows
make:
  stage: make
  image: node:${NODE_VERSION}-windowsservercore-ltsc2022
  script:
    - cp -r dist/ .  # Копируем артефакты из предыдущего шага
    - npm install
    - npm run make
  artifacts:
    paths:
      - out/
    expire_in: 1 week
  dependencies:
    - build

# Шаг 3: Подготовка артефактов для скачивания
release_artifacts:
  stage: artifacts
  script:
    - echo "Preparing artifacts for download..."
  artifacts:
    paths:
      - out/
    expire_in: 1 month
  dependencies:
    - make

