name: Build and Release Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create installers
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installer-${{ matrix.os }}
          path: out/
          retention-days: 5  # Автоматическое удаление артефактов через 5 дней